### ISSUE TITLE
Support for Ubuntu 20.04

### ISSUE THREAD

**Issue by gcollins-spark** [andrewinci/insulator2#681]
The built artifacts use a version of C libs that's too new for Ubuntu 20.04, so although it installs it won't run

Is the solution for this just to build the project on an older Linux version so it is packaged with earlier C libs? Newer Ubuntu versions like 22 would be backwards compatible?

I tried to build locally following some instructions but couldn't get everything set up right

Error when running:

    /usr/bin/insulator-2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/insulator-2)
    /usr/bin/insulator-2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/bin/insulator-2)
    /usr/bin/insulator-2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/bin/insulator-2)

**Comment by andrewinci** [comment]
Hey @gcollins-spark, I tried to downgrade the GH action runner for ubuntu to 20.04. Could you try if the latest artefacts works on your system? https://github.com/andrewinci/insulator2/actions/runs/7811080360/artifacts/1226106359

**Comment by gcollins-spark** [comment]
Thanks @andrewinci it works

**Comment by gcollins-spark** [comment]
Thanks @andrewinci it works :tada:
